// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowCarrot.Data;

#nullable disable

namespace YellowCarrot.Migrations
{
    [DbContext(typeof(CarrotContext))]
    partial class CarrotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YellowCarrot.Model.Ingridient", b =>
                {
                    b.Property<int>("IngridientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngridientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recipeId")
                        .HasColumnType("int");

                    b.HasKey("IngridientId");

                    b.HasIndex("recipeId");

                    b.ToTable("ingridients");

                    b.HasData(
                        new
                        {
                            IngridientId = 1,
                            Name = "Vetemjöl",
                            Quantity = "2 1/2 dl",
                            recipeId = 1
                        },
                        new
                        {
                            IngridientId = 2,
                            Name = "Salt",
                            Quantity = "1/2 tsk",
                            recipeId = 1
                        },
                        new
                        {
                            IngridientId = 3,
                            Name = "Mjölk",
                            Quantity = "6 dl",
                            recipeId = 1
                        },
                        new
                        {
                            IngridientId = 4,
                            Name = "Ägg",
                            Quantity = "3 st",
                            recipeId = 1
                        },
                        new
                        {
                            IngridientId = 5,
                            Name = "Smör",
                            Quantity = "(till Stekning)",
                            recipeId = 1
                        },
                        new
                        {
                            IngridientId = 6,
                            Name = "Smör",
                            Quantity = "(till Stekning)",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 7,
                            Name = "Smör",
                            Quantity = "100g",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 8,
                            Name = "Ägg",
                            Quantity = "2 st",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 9,
                            Name = "Strösocker",
                            Quantity = "2 1/2 dl",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 10,
                            Name = "Kakao",
                            Quantity = "3 msk",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 11,
                            Name = "VaniljSocker",
                            Quantity = "2 tsk",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 12,
                            Name = "VeteMjöl",
                            Quantity = "1 1/2 dl",
                            recipeId = 2
                        },
                        new
                        {
                            IngridientId = 13,
                            Name = "Salt",
                            Quantity = "1 krm",
                            recipeId = 2
                        });
                });

            modelBuilder.Entity("YellowCarrot.Model.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.ToTable("recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            RecipeName = "Pannkaka"
                        },
                        new
                        {
                            RecipeId = 2,
                            RecipeName = "Kladkaka"
                        });
                });

            modelBuilder.Entity("YellowCarrot.Model.Tags", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recipeId")
                        .HasColumnType("int");

                    b.HasKey("TagId");

                    b.HasIndex("recipeId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("YellowCarrot.Model.Ingridient", b =>
                {
                    b.HasOne("YellowCarrot.Model.Recipe", "Recipe")
                        .WithMany("Ingridients")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("YellowCarrot.Model.Tags", b =>
                {
                    b.HasOne("YellowCarrot.Model.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("YellowCarrot.Model.Recipe", b =>
                {
                    b.Navigation("Ingridients");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
